### ISSUE TITLE
Only count naturally generated ores 

### ISSUE THREAD

**Issue by HyplexMC** [LMBishop/Quests#116]
**Description of Feature**
Ok so i own a Semi-Vanilla Server and i just recently added these Quests to the server and before we added it me and my Admin had a discussion about how players can easily cheat on the quests. So each quest has a type and for now i will use the mining as a example as that's where my issue is at, so lets say you have the blockbreakcertain task type and your intention is for players to go out and mine for the ores and go caving ect. but players can cheat this by mining a few blocks and then going back to their base and placing the blocks down and mining them again over and over again to quickly cheat the quest and gain the rewards. My feature request would to be to add a functionality where you can set the quest to only be naturally generated ores so that way if a player mines the ore and places it back down and mines it again it wont count towards the progress of the quest and only untouched naturally generated ore will count towards the progress.

The reverse-if-placed: true is simply not enough once again this is the lazy way of fixing this issue, i personally dont know a way to exploit this but i am sure players can find a way. We need something that's 100%. Looking at other issues people have made they have made it clear that this is not enough and this is a MAJOR issue with the plugin and needs to be properly addressed. 

Players being able to mine the same block over and over again completely ruins the system and the quests entirely and theirs absolutely no way to 100% moderate this so it doesn't happen.

Update: ive tested the `reverse-if-placed: true` and it doesn't work, it still counts it towards the progression.

**Comment by FesterHead** [comment]
The general idea would be to keep track of all placed blocks (or set a list of blocks to keep track of) and see if any player broken blocks are in the list.  If so, remove from the list and don't give credit.  Else give credit.

The [Jobs Reborn](https://www.spigotmc.org/resources/jobs-reborn.4216/) uses this algorithm.
```
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: true
    # For how long in days to keep block protection data in data base
    # This will clean block data which ones have -1 as cooldown value
    # Data base cleanup will be performed on each server startup
    # This cant be more then 14 days
    KeepDataFor: 14
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: true
      timer: 10
```

For inspiration:  https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/config/BlockProtectionManager.java

The only way this will be 100% is if the date range is unbounded which may lead to performance issues.
If a user lays down a line of x iron ore blocks and two weeks later breaks them to get credit...  Have fun storming the castle.
