### ISSUE TITLE
Problem with interacting with npc's (as in Citizens plugin)

### ISSUE THREAD

**Issue by fadexdev** [LMBishop/Quests#123]
I slightly modified the plugin for my own needs, including modifying TaskType for Citizens plugin for my own NPC plugin and added dialogs. When I create tasks consecutively in a quest file, for example:
```
tasks:
   task1:
     type: "npc_interact"
     npc-name: "& 6NPC1"
     dialogue: "&cQUEST &8» &aNPC1 talk something 1"
   task2:
     type: "npc_interact"
     npc-name: "& 6NPC1"
     dialogue: "&cQUEST &8» &aNPC1 talk something 2"
   task3:
     type: "npc_interact"
     npc-name: "& 6NPC1"
     dialogue: "&cQUEST &8» &aNPC1 talk something 3"
```
The code of the CitizensInteractTaskType.java class is identical except for changing the NPCRightClickEvent event for my own event. The problem is as follows: when I click on an NPC, all the tasks are done at once. How can this be fixed quickly? I have tried various methods with taskProgress but cannot find an effective solution. 

I added `break;` in a `for (Task task: quest.getTasksOfType (super.getType ()))` loop, tasks are performed one at a time on each click, but they mix and do not execute consecutively.
