### ISSUE TITLE
Deal Damage Task Type Progress Lore Goes Above Required Amount

### ISSUE THREAD

**Issue by meowsome** [LMBishop/Quests#146]
**Description of Error**
The progress amount in the lore of a quest for the amount of damage dealt using the "dealdamage" task type does not stop at the required amount specified in the task. It stops once it goes above the required amount, but displays that value instead of the required value.

**To Reproduce**
Make a quest with this config:
```
tasks:
  deal_damage:
    type: "dealdamage"
    amount: 200
display:
  name: "test"
  lore-normal:
    - "test"
  lore-started:
    - ""
    - "&7Progress:"
    - "&7{deal_damage:progress}/200 damage inflicted"
  type: "DIAMOND_SWORD"
rewards:
  - "blahblah"
options:
  category: "test"
  repeatable: true
  cooldown:
    enabled: true
    time: 4320
  sort-order: 1
```
The quest works as normal, but the value for the progress of damage dealt in the lore goes above the required amount when it should stop at 200.

**Screenshots**
https://prnt.sc/yfyuu0
https://prnt.sc/yfzqzk

**Server (please complete the following information):**
 - Minecraft Version: 1.16.1
 - Mod Name: Paper 138

**Plugin (please complete the following information):**
 - Version: 2.11

**Stacktrace**
N/A
