### ISSUE TITLE
Suggestion: Conditions for Quests

### ISSUE THREAD

**Issue by supermem99** [LMBishop/Quests#184]
Hey,
It will be very helpful, if there is a possibility to add conditions for single Quests.

Like placeholder conditions 

Thanks

**Comment by Folas1337** [comment]
I would also love to see this. I know this is an old issue and the initial description I think is lacking, so here's my understanding of the idea.

```yaml
tasks:
  task1:
    type: "smelting"
    amount: 10
    item: IRON_INGOT
    condition_placeholder: %player_biome%
    condition_evaluates: PLAINS
    #condition_operator: GREATER_THAN
```

The operator here isn't required but it's exactly the same logic as you're using in [PlaceholderAPI Evalues Task Types](https://quests.leonardobishop.com/task-types/placeholderapi_evaluate-(task-type).html)
This should obviously be added to all task types, internal as well as external!

It would add SO MUCH MORE flexibility to the plugin and I think setting it as "low priority" should be reevaluated :)
