### ISSUE TITLE
CustomModelData support

### ISSUE THREAD

**Issue by Wupin** [LMBishop/Quests#193]
### Reason for Addition

more customization

### Description of Feature

Can you add support for CustomModelData, so we can use custom textures on items. Simple idea, shouldn't take that much work.

### Alternative Solutions

The alternative solution is to retexture default items, which is not possible if you have a survival server.

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Quests already supports custom model data, it would look something like this
```yaml
  item:                                 # SPECIFIC item with name and lore
    name: "&cSpecial Beef"
    type: "RAW_BEEF"
    lore:
     - "&7This is a special type of beef"
    custommodeldata: 12345 
```
