### ISSUE TITLE
Formatting by slots

### ISSUE THREAD

**Issue by widify-test** [LMBishop/Quests#200]
### Description of Feature

I would like to see quests start not from slot 0, but, for example, from slot 10 to 16;19-25, or the slot can be configured in the configuration for convenience

**Example:**
![изображение](https://user-images.githubusercontent.com/73692598/124580923-479f2600-de59-11eb-8fba-997a9162fceb.png)

### Alternative Solutions

There is nothing in the configuration of this, so it does not look particularly nice

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
You can already do this, see the wiki: https://github.com/LMBishop/Quests/wiki/Custom-GUI-Items

The following achieves that effect:
```yaml
# Here you can add custom items to the quest menu
# Categories & quests will fill empty slots
custom-elements:
 "c:examples": # apply to the category "examples"
   0:
     spacer: true
     repeat: 9
   17:
     spacer: true
     repeat: 2
   26:
     spacer: true
     repeat: 2
   35:
     spacer: true
     repeat: 2
   44:
     spacer: true
```
