### ISSUE TITLE
Wheat, Carrot, Potato, Beetroot not working in breakblockcertain.

### ISSUE THREAD

**Issue by dustinxavier** [LMBishop/Quests#212]
### Description of Bug

I'm using 1.12.2 and the wiki said: **"Farm a set amount of a specific crop. For versions under 1.13, use blockbreakcertain with data codes."** but when I set type = WHEAT and the data = 7 (still not working if removed)" is not working as expected, also not working with any crop which has aged. My configuration:
```
tasks:
  farm1:
    type: "blockbreakcertain"
    amount: 10                            
    block: WHEAT 
    reverse-if-placed: true 
```
And I guess that blockbreakcertain will causing some lifehack/trick if we cant check the age of the crop.

### Steps to Reproduce

1. Set the type of blockbreakcertain to "WHEAT"
2. Save the quest
3. Accepted the quest
4. Break a wheat crop
5. Nothing happen.

### Environment

- Minecraft version: 1.12.2
- Server software: Spigot 1.12.2
- Quests version: 3.5

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
