### ISSUE TITLE
Cooldown Time not showing.

### ISSUE THREAD

**Issue by PaDo90** [LMBishop/Quests#220]
### Description of Bug

Hello, I have the problem that the cooldown time is not displayed correctly. Only "messages.time-format" is displayed but not the time how long the cooldown is still active. (See screenshot) How can I fix this problem?

### Steps to Reproduce

Screenshot: https://imgur.com/NAoih2v

```
quest-cooldown-display:
    name: "&e&nCooldown"
    lore:
    - "&7Du hast diese Quest (&e{quest}&7)"
    - "&7vor kurzem erledigt und musst nun &e{time}"
    - "&7warten, um sie erneut abschließen zu können."
```

### Environment

- Minecraft version: 1.16.5
- Server software: PaperMC
- Quests version: 3.6.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
