### ISSUE TITLE
Plugin don't know Enchantingtables

### ISSUE THREAD

**Issue by PaDo90** [LMBishop/Quests#224]
### Description of Bug

I have setup the following Quest:

```
tasks:
  books:
    type: "blockplacecertain"
    amount: 16
    block: "BOOKSHELF"
  etable:
    type: "blockplacecertain"
    amount: 1
    block: "enchanting_table"
display:
  name: "&9&nBau Quest:&r &e#11"
  lore-normal:
  - "&7Diese Quest erfordert von dir etwas zu bauen,"
  - "&7bevor du die Belohnung erhälst."
  - "&r"
  - "&6◆ &eAufgabe:&r &7Baue eine Verzauberungs Station."
  - "&6◆ &eFortschritt:&r"
  - "        &6◆ &7{books:progress}/16 Bücherregale"
  - "        &6◆ &7{etable:progress}/1 Verzauberungstisch"
  - "&6◆ &eBelohnung:&r &a200 Erfahrungspunkte"
  - "&r"
  lore-started:
  - "&a&k;&r&f&k;&r &a(!) Du hast diese Quest bereits gestartet."
  type: "BOOK"
rewards:
  - "xp give {player} 200"
options:
  category: "building"
  requires: []
  repeatable: true
  cooldown:
    enabled: true
    time: 2880
  sort-order: 11
```

After reload I get this warning ingame:
W: Material 'enchanting_table' does not exist

When I use command /give NAME enchanting_table 1 I get one enchantingtable so I think it's not the wrong ID.

### Steps to Reproduce

Screenshot: https://imgur.com/cukU5xZ

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
