### ISSUE TITLE
New Task-type: Multiple/Bulk NPC interactions

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#241]
### Reason for Addition

This would facilitate RPG servers (and other server types) to allow people to interact with multiple NPCs as a part of the same quest without overcomplicating and making a quest for reach NPC. Something similar to Hypixel's Talk to the Villagers, where you have to interact (or click) specific amount of villagers to complete the Quest.

### Description of Feature

It's also explained above, but basically allow us to have multiple NPC's as part of the citizens_interact task, or even create a new task type, for example citizens_interact_multiple;

citizensinteractmultiple:
  type: "citizens_interact_multiple"
  npc-names: "NPC1, NPC2, NPC3, NPC4, ..." 
   

### Alternative Solutions

I do not see a alternative solution to making this as for right now.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
I've never played that Hypixel game mode, but wouldn't having multiple citizens_interact tasks in the same quest achieve this?

**Comment by KhrysAK47** [comment]
The issue with this would be the progress wouldn't be displaying properly due to it being of the same type. But I can try it out if you want?

**Comment by LMBishop** [comment]
I'm still not sure what the issue is, you can have a quest set up like this:

```yaml
tasks:
  interactwithbob:
    type: "citizens_interact"
    npc-name: "Bob"
  interactwithkatie:
    type: "citizens_interact"
    npc-name: "Katie"
display:
  name: "&cTalk to Bob and Katie"
  lore-normal:
    - "..."
  lore-started:
    - ""
    - "&7Spoken to Bob: {interactwithbob:complete}"
    - "&7Spoken to Katie: {interactwithkatie:complete}"
  type: "GRASS_BLOCK"
rewards:
  - "eco give {player} 10"
options:
  # ...
```
and it should display the progress (or rather the completion state) just fine
