### ISSUE TITLE
List option for mob: and item:

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#266]
### Reason for Addition

You can define multiple blocks in a list, why not animals and items?

It makes sense to be able to define multiple animals to kill, or a list of items to deliver. 

### Description of Feature

```
murderanimals:
    type: "mobkillingcertain"
    amount: 48
    mobs: 
     - COW
     - CHICKEN
     - PIG
     - SHEEP
     ```
     Example of what the quest would look like.

### Alternative Solutions

Pretty sure there is no way to do this.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
