### ISSUE TITLE
Armor for type "inventory" not detecting.

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#282]
### Description of Bug

When trying to detect if the player has chainmail armor in their inventory it fails, as the armor has NBT tags by default. (chain armor is only dropped from mobs and can't be crafted) And even when disenchanted and repaired the item doesn't get recognized 

Weird thing is boots work for some reason. but nothing else does

### Steps to Reproduce

```
chainmail:
    type: "inventory"
    item: CHAINMAIL_HELMET
    amount: 1
    remove-items-when-complete: true
```

doesn't work

### Environment

Minecraft version: 1.17.1
Server software: Paper version git-Paper-135 (MC: 1.17.1)
Quests version: Quests version 3.9

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Can you try importing the item using the import feature and pasting here the exact file which is generated

**Comment by Nesseley** [comment]
Heres a item gotten in survival:
```
type: raw
item:
  ==: org.bukkit.inventory.ItemStack
  v: 2730
  type: CHAINMAIL_BOOTS
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    Damage: 177
```

And here is the item gotten from creative menu.
```
type: raw
item:
  ==: org.bukkit.inventory.ItemStack
  v: 2730
  type: CHAINMAIL_BOOTS
```
