### ISSUE TITLE
what dont work?

### ISSUE THREAD

**Issue by RetamrCZ** [LMBishop/Quests#292]
### Description of Bug

Hello, my new file for quest dont work.

### Steps to Reproduce

Here is the file:

```
mobkillingzombie:
  type: "mobkillingcertain"
  amount: 23
  mob: ZOMBIE
  worlds:
   - "survival"
   - "world"
   - "world_nether"
   - "world_the_end"

display:
  name: "&aHunting &b１"
  lore-normal:
    - "&cThis category is designed to show you the different"
    - "&cattributes a quest can have."
    - ""
    - "&7This quest requires you to:"
    - "&7 - Break &f30 blocks&7."
    - ""
    - "&7Rewards:"
    - "&7 - &f10 &7diamonds."
  lore-started:
    - ""
    - "&7Your current progression:"
    - "&7 - &f{mobkillingzombie:progress}&7/30 blocks broken."
  type: "WOODEN_SWORD"

rewards:
  - "give {player} diamond 10"

placeholders:
  description: "&7Zabij &a8 creeperů&7, &934 spiderů&7, &c19 skeletonů &7a &b23 zombíků&7."
  progress: " &f{huntingskeleton:progress}&7/&f19 &8| &f{huntingzombie:progress}&7/&f23 &8| &f{huntingcreeper:progress}&7/&f8 &8| &f{huntingspider:progress}&7/&f34"

options:
  category: "vip"
  repeatable: true
  cooldown:
    enabled: true
    time: 60
  sort-order: 1
```

### Environment

- Minecraft version: 1.17.1
- Server software: PurpurMC
- Quests version: 3.9.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
