### ISSUE TITLE
Cannot complete quest out of order

### ISSUE THREAD

**Issue by witloofashley** [LMBishop/Quests#293]
### Description of Bug

When I perform one quest after the other it works perfectly. but if I want to start these quests in a same time (quests accepted) none of these want to complete. 

It appears that I Have to do the quest in the NPC creation order. I created NPC1 then NPC2 then NPC3, Whatever the order of the quests creation, I cant complete any quests if I start to interact with NPC2.

### Steps to Reproduce

create npc 1 npc 2 npc3
create three quests without requirement : task citizen_deliver
start the three quests in same time
try to perform the three quest in other order

### Environment

- Minecraft version:
This server is running Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38

- Server software:
Paper

- Quests version:
Quests version 3.9.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

quest 1 NPC ID 35 :
```
tasks:
  citizens_deliver:
    type: "citizens_deliver"
    npc-name: "Commandant Klarc"
    item:
      quest-item: "iledepragout"
    amount: 1
    remove-items-when-complete: true
display:
  name: "Retour de livraison - Commandant"
  lore-normal:
  - "J'ai fini la cuisine. Pouvez vous livrer,"
  - "les plats s'il vous plait ? Celui ci au comandant."
  lore-started:
  - " "
  - "Apportez 1 ragout du chef au Comandant Klarc"
  type: "PAPER"
startstring: 
rewards:
- "cui give {player} pa 3
rewardstring:
- "§7§o+ 3 pièces d'argent"
options:
  category: "starter"
  requires:
  - "starter53"
  repeatable: false
  sort-order: 54

```
Quest 2 NPC ID 36:
```
tasks:
  citizens_deliver:
    type: "citizens_deliver"
    npc-name: "Frère Lucas"
    item:
      quest-item: "iledepragout"
    amount: 1
    remove-items-when-complete: true
display:
  name: "Retour de livraison - Frère Lucas"
  lore-normal:
  - "J'ai fini la cuisine. Pouvez vous livrer,"
  - "les plats s'il vous plait ? Celui ci au curé."
  lore-started:
  - " "
  - "Apportez 1 Ragout du chef à Frère Lucas"
  type: "PAPER"
startstring: 
rewards:
- "cui give {player} pa 3"
rewardstring:
- "§7§o+ 3 pièces d'argent"
options:
  category: "starter"
  requires:
  - "starter53"
  repeatable: false
  sort-order: 55
```

quest 3 NPC ID 84 :
```
tasks:
  citizens_deliver:
    type: "citizens_deliver"
    npc-name: "Capitaine Webber"
    item:
      quest-item: "iledepragout"
    amount: 1
    remove-items-when-complete: true
display:
  name: "Retour de livraison - Capitaine"
  lore-normal:
  - "J'ai fini la cuisine. Pouvez vous livrer,"
  - "les plats s'il vous plait ? Celui ci au capitaine."
  lore-started:
  - " "
  - "Apportez 1 Ragout du chef au Capitaine Webber"
  type: "PAPER"
startstring: 
rewards:
- "cui give {player} pa 3"
rewardstring:
- "§7§o+ 3 pièces d'argent"
options:
  category: "starter"
  requires:
  - "starter53"
  repeatable: false
  sort-order: 56
```
