### ISSUE TITLE
Custom Model Data support

### ISSUE THREAD

**Issue by zBuilderch** [LMBishop/Quests#302]
### Reason for Addition

It would be useful for servers with resource packs so that they have the possibility to match the style of Quest's GUI menu with that of the other GUI menus.

### Description of Feature

I would add a "#" after the item name for the custom model data. If there is no "#" after the item type it will return the normal item.
```
  back-button:
    name: "&cMain Menu"
    type: "BARRIER"
  page-prev:
    name: "&bPrevious Page"
    type: "PAPER#1"
  page-next:
    name: "&bNext Page"
    type: "PAPER#2"
```
![image](https://user-images.githubusercontent.com/95584280/144757399-7225446d-fb8a-4215-9c33-e67b2c9a0a88.png)

### Alternative Solutions

I don't know other alternative solutions.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
