### ISSUE TITLE
deepslate_ORES

### ISSUE THREAD

**Issue by Trinchezito** [LMBishop/Quests#313]
### Description of Bug

It doesn't recognize the deepslate_ORES names. 
Like Diamond_ore is now on 1.18 deepslate_diamond_ore.

### Steps to Reproduce

Make a mining quest with deepslate_diamond_ore

Go mine deepslate_diamond_ore and it doesn't recognize it. It only recognize diamond_ore but on 1.18 that's not possible to find anymore.

### Environment

- Minecraft version: 1.18
- Server software:
- Quests version: 3.9.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
@Trinchezito
```
  blockbreakiiiiiiing:
    type: blockbreak
    amount: 10
    block:
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
```

https://github.com/LMBishop/Quests/assets/46192742/36a3543f-61aa-42d7-801b-219c04cc57f9

@LMBishop can be closed
