### ISSUE TITLE
Custom Item for each Completed Quest

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#337]
### Reason for Addition

I would love to use some CustomModelData stuff to make greyed'out items for my repeatable quests while they are on cooldown. Right now they just turn into BOOK which works great for my main Quest-line. But not my repetitive quest-line 

### Description of Feature

Add a setting for each quest under the options: part of the quests.

Example: with a reskinned diamond with customitemdata 2.
```
options:
  category: "Repetative"
  repeatable: true
  cooldown:
    enabled: true
    time: 960
  sort-order: 1
  quest-completed-display:
    type: "DIAMOND"
    CustomItemData: 2
```
This would make the item displayed into my custom item when the quest is on cooldown.
If not set in the options, it should default to the `quest-completed-display` from config.yml

### Alternative Solutions

-

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
