### ISSUE TITLE
custom-elements add clickable items to execute commands

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#341]
### Reason for Addition

I would love to display a lot of information to my player, however the GUI hover thing is not great for this. As if they gave too large GUI size in their settings the text will go off the screen.

Let us add custom-elements that the player can click to run commands from the console.

### Description of Feature

Example of how the config would look.
```
7:
  display:
    name: "Information"
    lore:
      - "Click me to get more information"
    commands:
      - "tell <player> this is some information"
    type: "BELL"
```

### Alternative Solutions

-

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
