### ISSUE TITLE
Missing placeholder for filename

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#346]
### Reason for Addition

I want to display when a quest was completed inside the   quest-completed-display. I've tried this, which will just tell me that "Quest 1" is not a quest. As {quest} pulls the displayname of the quest.
```
  quest-completed-display:
    name: "&a&l {quest} Completed"
    lore: 
    - "&7%quests_quest:{quest}_completiondate%"
    type: "BOOK"
```

### Description of Feature

Add a placeholder {questname} to grab the filename.

### Alternative Solutions

-

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
