### ISSUE TITLE
Add option to hide category in main menu (category menu)

### ISSUE THREAD

**Issue by ArtifactyNight** [LMBishop/Quests#355]
### Reason for Addition

Because I want to player open that quest category in NPC only

### Description of Feature

```yml
categories:
  examples:
    display:
      hide: true # <-- hide this category from main menu
      name: "&cExample Quests"
      lore:
        - "&7This category contains example quests"
        - "&7which are commented in the config."
        - "&7The comments should guide you with"
        - "&7how the config works."
        - ""
        - "&cIt is highly recommended you read this"
        - "&csection and all the comments so you can"
        - "&cmake the most of this plugin."
      type: "WATER_BUCKET"
```

### Alternative Solutions

None

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
