### ISSUE TITLE
customdatamodels

### ISSUE THREAD

**Issue by dinobossytnew** [LMBishop/Quests#373]
### Reason for Addition

2022 :V 

### Description of Feature

Adding CustomDataModels is the most needed.

### Alternative Solutions

add support ItemsAdder

ORAXEN IS VERY POOP!

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

### Other

NULL

**Comment by LMBishop** [comment]
> Adding CustomDataModels is the most needed.

https://github.com/LMBishop/Quests/wiki/Defining-items#Custom-model-data

**Comment by dinobossytnew** [comment]
not work in category.yml

**Comment by LMBishop** [comment]
Show me what you have tried

**Comment by dinobossytnew** [comment]
https://mcpaste.io/6dfbeea9b82412ff

**Comment by Nesseley** [comment]
Custommodeldata in Category works just fine for me.
```
  utfordring:
    display:
      name: "&6&l Utfordringer "
      type: "SHEARS"
      custommodeldata: 1
````
