### ISSUE TITLE
Task "inventory" broken after last update.

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#375]
### Description of Bug

After the last addition here you don't need to deliver all items at once the "INVENTORY" task is broken. 
You don't need to gather more than 1 item to complete the quest.

### Steps to Reproduce

```
  deliver:
    type: "inventory"
    amount: 200
    item: BONE
    remove-items-when-complete: true
```
    
Put 1 BONE in your inventory, keep opening /q to complete the quest with only 1 bone gathered.

### Environment

- Minecraft version: 1.18.2
- Server software: git-Paper-267 (MC: 1.18.2)
- Quests version: 3.11

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
