### ISSUE TITLE
Issue with Custom GUI Items

### ISSUE THREAD

**Issue by Sixsoul** [LMBishop/Quests#378]
### Description of Bug

Here is my configuration:
```
  "c:daily":
    0:
      display:
        name: "&7 "
        type: "PAPER"
        custommodeldata: 10056
    8:
      display:
        name: "&7 "
        type: "PAPER"
        custommodeldata: 10056
    10:
      display:
        name: "&7 "
        type: "PAPER"
        custommodeldata: 10056
      repeat: 7
```
Here is what it looks like:
![image](https://user-images.githubusercontent.com/83363206/164875049-2bf12a31-08b4-49ff-a5a5-8b13e27d9b02.png)

I want to fill the bottom row next to the back button so it's to standard with the rest of my server's GUIs, but Quests pushes the button down a row always and I don't think this should be the case.

### Steps to Reproduce

Use the configuration I pasted above and you will replicate the issue.

### Environment

- Minecraft version: 1.18.2
- Server software: Paper 1.18.2
- Quests version: Latest - 3.11

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
