### ISSUE TITLE
Playerkilling task type not working

### ISSUE THREAD

**Issue by TeQTabanca** [LMBishop/Quests#380]
### Description of Bug

```
tasks:
  playerkilling:
    type: "playerkilling"
    amount: 3
```

**I set it to. but when I kill the player the counter does not advance.Additionally, I reloaded the plugin's settings using the server and the "/quest a reload" command, but it didn't work.**

### Environment

- Minecraft version: 1.12.2
- Server software: Java 11
- Quests version: 3.11

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
