### ISSUE TITLE
Cannot bind gui actions on the same button

### ISSUE THREAD

**Issue by emmanuelvlad** [LMBishop/Quests#396]
### Description of Bug

Cannot use the same button for actions.

https://github.com/LMBishop/Quests/blob/master/bukkit/src/main/java/com/leonardobishop/quests/bukkit/menu/QuestQMenu.java#L231

Once it goes in the condition, it will not check other actions.

### Solution
If quest is already started then check if the `event.getClick()` is equal to another action (track or cancel)

### Steps to Reproduce

in `config.yml` set:
```yaml
  gui-actions:
    start-quest: "LEFT"
    track-quest: "MIDDLE"
    cancel-quest: "LEFT"
```

### Environment

- Minecraft version: 1.18.2
- Server software: paper-312
- Quests version: 3.12-547bb09

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
