### ISSUE TITLE
Issue with blockbreakcertain

### ISSUE THREAD

**Issue by Sixsoul** [LMBishop/Quests#398]
### Description of Bug

Just can't get it to track certain blocks. For example:

```
  task1:
    type: "blockbreakcertain" 
    blocks:
    - DARK_OAK_LOG
    - DARK_OAK_WOOD
    amount: 5000   
    reverse-if-placed: false
    check-coreprotect: true
    check-coreprotect-time: 3600
    worlds:
    - "world"
```
This will not track DARK_OAK_LOG no matter what I do. It's the exact same setup that I've made for every other wood type for different quests, and those work while this one does not. No errors on reload or anything like that.

### Steps to Reproduce

1. Create a blockbreakcertain using DARK_OAK_LOG.

2. Realize you can't complete the quest because it does not work.

### Environment

- Minecraft version: 1.18.2
- Server software: Paper
- Quests version: 3.12-547bb09

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
