### ISSUE TITLE
multiple items for one quest

### ISSUE THREAD

**Issue by MrMorganCz** [lmbishop/Quests#40]
**Description of Feature**
use multiple items for one quest, for example, if I want all Horse Armory (Gold, iron.diamond) to work.

```
  nightmarequest5:
    tasks:
      riddle:
        type: "inventory"
        item: 417
        amount: 1
        remove-items-when-complete: false
        type: "inventory"
        item: 418
        amount: 1
        remove-items-when-complete: false
```
