### ISSUE TITLE
Bug Report: Tasktype walking not registering mode: minecart

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#464]
### Description of Bug

The tasktype walking is not registering mode: minecart
```
walking:
    type: "walking"
    distance: 10000
    mode: minecart
```

### Steps to Reproduce

-

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
