### ISSUE TITLE
Category custom elements only apply to page one of the category

### ISSUE THREAD

**Issue by Sixsoul** [LMBishop/Quests#472]
### Description of Bug

For whatever reason, past page one of a category all of the custom elements are just completely messed up, they either aren't place, placed in the wrong spot, or, I don't even know, it is a mess.

### Steps to Reproduce

Here, in this video I replaced what is meant to be filler with PAPER so you can see it. When I turn to page 2 it just puts completely random elements and I don't understand, I do not have anything configured like this.

Video:  https://streamable.com/1153sw

My config:

```
"c:achievement":
    0:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    9:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    18:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    27:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    36:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    7:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    16:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    25:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    34:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    43:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    45:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 1
    51:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      repeat: 2
    47:
      display:
        name: "&7 "
        type: "PAPER"
        # custommodeldata: 10384
      commands:
        - "cp quests {player}"
```

### Environment

- Minecraft version: 1.18.2
- Server software: Paper
- Quests version: 3.13.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
