### ISSUE TITLE
Citizen_interact task : Unable to complete quest by clicking NPC

### ISSUE THREAD

**Issue by witloofashley** [LMBishop/Quests#501]
### Description of Bug

_I'm sorry if the issue has already been reported, i Did not find it_

I used to create many quests on version 1.17.1 of the game (paper build). at this time everything worked. after a break I updated my game to 1.19.3. i updated all my plugins.

But now, I cannot complete any quest where I have to interact with NPC (citizen_interact and citizen_deliver tasks)
When I click on the npc nothing happens
No error in console is shown too.

I use Shopkeepers plugin too but, even if I uninstall it, NPC still dont work

I tried to re-create quest > same behavior
I tried to wipe Citizens database and recreate the NPC > Same behavior
I tried to stop every NPC plugins (Shopkeeper, sentinel, citizens and denizen) > same behavior
i tried to put npc-id instead of the name > same behavior

### Steps to Reproduce

Create npc named Billy
npc-id: 1
Create quest below
start game
test the quest > nothing

------
Here is the quest : 
------
```
tasks:
  citizens_interact:
    type: "citizens_interact"
    npc-name: "Billy"
display:
  name: "§eBilly"
  lore-normal:
  - "§fBilly est seul depuis le deces de"
  - "§fses parents. il tien sa ferme avec"
  - "§fbeacoup de courage mais il y a "
  - "§fbeaucoup a faire. Un coup de main"
  - "§fne serait pas de reffus."
  lore-started:
  - "§7 "
  - "§7Allez voir Billy"
  type: "PAPER"
startstring: 
rewards:
- "cui give {player} pc 1"
- "give {player} oak_planks 4"
- "tr {player} <Billy> Bonjour !"
rewardstring:
- "§7§o+ 1 pièce de cuivre"
- "§7§o+ 4 planches"
placeholders:
  description1: "Allez voir Billy"
  progress1: ""
  description2: ""
  progress2: ""
  description3: ""
  progress3: ""
options:
  category: "billy"
  requires: []
  repeatable: false
  sort-order: 1
  quest-autostart: true
```

-----
here is the npc created:
-----
```
  '25':
    metadata:
      cached-skin-uuid-name: c72d9421-29f3-4e2d-b01b-277f1b382e41
      cached-skin-uuid: 05b39a97-a9e4-4a17-8741-bedf16201f2f
      nameplate-visible: 'false'
    name: Billy
    uuid: 47438781-dce4-4d90-adda-ef607c32329b
    traits:
      skintrait:
        fetchDefaultSkin: true
        signature: RWlS+SDEJ2wfSt6W5zqpZj4+UBLC/xaDhKatlxuQdMokxJ4LXjxwULTCFkjbUi4Hbe1grRMiRKwnBVZeRQJUQtCfG6IxTW5QhZVe6JTChrMDxXk2pCLWwGGbxUjurTaB8QccAnWAK62Q4pQLPk6K3Ym+cNT6RaTvzHewRNOoUrL/0jO4zE+va3I5qokyuBRylqYroDdlvQ5o3syRryK1UECqNgUVGkWl1YW5jNKKjY9djLRm6AQnthYc9LZGuAM/2v0VsdnGfHjh+5stZsFqzLiF/BH59Dlwl8eb+0nqKQchFDjoNF9ltgSewAYMGEOgSW3HfAHQbU5fwrUe3UoR5+c4iosORi0jKqszAUQjtmaFzDqdncLyBs8q5aDsXbv+U94WEpdC9KOBIbyg6vKduEQlNjLAbq+oIdCnqGfI98kHl+Hflkx1PWpQbN1jOiacl8TSwBGu2jPH/DI+se0QYlRWCX02YMQucplWEmTcvLYTRmi01bMpNSjAgP6M9IgK3zoFwVouZWOx1Xcszl0GdOrAjJE/KicjCIFpMo/wp65wx05XByIsr1r7jRxMoVFz4wS2VnXz399kHBeH3uOdtn+aob8C1mKoAr5S6ovLo+9pLfLKNXh8ydA9Mk2/0FIbhDv4m2obHk8ve9m6WTTT43N61wJsvtJQ+KiI89f8yMo=
        skinName: c72d9421-29f3-4e2d-b01b-277f1b382e41
        textureRaw: ewogICJ0aW1lc3RhbXAiIDogMTYzMDE5NjI0NTY3OCwKICAicHJvZmlsZUlkIiA6ICI5OTdjZjFlMmY1NGQ0YzEyOWY2ZjU5ZTVlNjU1YjZmNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJpbzEyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Y3N2ZjNjA1NGEyN2Q1OWViNDlmYzk3MWQ1MjA1ZGU5Mzg5M2FmZWQ1NTJiZTA3MTRjZTJjMDM3OWJjMzA1MmYiCiAgICB9CiAgfQp9
        updateSkins: false
      type: PLAYER
      spawned: true
      hologramtrait:
        direction: TOP_DOWN
        lineHeight: 0.26
        lines:
          '0': §2§lBilly
      lookclose:
        range: '5.0'
        disablewhilenavigating: true
        enabled: true
        enableRandomLook: false
        randomLookDelay: 60
        realisticlooking: false
        headonly: false
        perplayer: false
        randomSwitchTargets: false
        targetnpcs: false
        randomPitchRange:
          '0': -10.0
          '1': 0.0
        randomYawRange:
          '0': 0.0
          '1': 360.0
      location:
        bodyYaw: -14.55101
        world: iledep
        x: '545.5'
        y: '12.0'
        z: '-277.5'
        yaw: '-14.551'
        pitch: '0.0'
      mounttrait:
        mountedon: 28f27f09-05fd-4e64-b4b4-028f0d169211
      commandtrait:
        cost: -1.0
        executionMode: LINEAR
        experienceCost: -1.0
        hideErrorMessages: false
        persistSequence: false
        commands:
          '0':
            command: playsound minecraft:entity.villager.celebrate voice @p 546 12
              -276
            hand: RIGHT
            player: false
            op: false
            cooldown: 0
            globalcooldown: 0
            n: -1
            delay: 0
      owner:
        uuid: 49f73f47-1748-44f9-8dfb-cd1e9f95272f
      sneak:
        sneaking: false
    traitnames: location,sneak,lookclose,type,equipment,rotationtrait,hologramtrait,inventory,skintrait,commandtrait,owner,scoreboardtrait,spawned,mounttrait
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
```

### Environment

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version
Previous version: git-Paper-447 (MC: 1.19.3)
- Quests version: Quests-3.13.3-5a28efa

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other
Edit : Just to try I put my server in 1.19.4 Paper prerelease... all the citizens quests (interract and deliver) are not recognized anymore.

https://user-images.githubusercontent.com/88518839/224733634-1d1e36e5-38b2-4c90-8479-ee88b4bb1488.mp4
