### ISSUE TITLE
Add the plugin "PinataParty" in task type

### ISSUE THREAD

**Issue by NoltoxGit** [LMBishop/Quests#518]
### Description of Feature

Hello,
Would it be possible to add integration of the "[PinataParty](https://www.spigotmc.org/resources/59318/)" plugin for the amount of hits the player puts on the Pinata.

Exemple:
```yml
pinata:
  type: "pinataparty_hits"
  amount: 100                           # amount of damage inflicted (HP)
  worlds:                               # (OPTIONAL) restrict to certain worlds
  - "world"
```

### Reason for Addition

I ask this because it would encourage players during a quest to participate in putting a certain number of hits on the Pinata. :)

### Alternative Solutions

I tried with the "deal damage" task type but doesn't worked.

### Agreements

- [X] I am running the latest version of Quests
- [x] I am certain this request is unique and a similar issue is not currently open
