### ISSUE TITLE
Consuming bug

### ISSUE THREAD

**Issue by FunSkelet** [LMBishop/Quests#532]
### Description of Bug

If there is an NBT tag on the item, then this item does not count in the quest

### Steps to Reproduce

Well, there's nothing to list, it just doesn't count...

### Environment

- Minecraft version: 1.20.1
- Server software: Purpur
- Quests version: 3.14.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Could you try with the `exact-match` option set to false?

**Comment by Krakenied** [comment]
@FunSkelet

```
  eeeeeeeeeeeee:
    type: "consume"
    amount: 1000000
    item: APPLE
    exact-match: false
```


https://github.com/LMBishop/Quests/assets/46192742/6b3b7642-6e9e-4eeb-b918-0753b01cf385

@LMBishop can be closed
