### ISSUE TITLE
Ignore Enchantments

### ISSUE THREAD

**Issue by MiniMoro98** [LMBishop/Quests#536]
### Description of Feature

I'm having some problems with completing some "inventory" type quests. Enchanted items are not considered by quests. It would be nice to add an index that allows you to ignore item enchantments to complete the quest

### Alternative Solutions

None

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Possibly related to #532

**Comment by MiniMoro98** [comment]
Where should I insert exact-match?
I tried to enter it in different ways but it didn't work.

**Comment by Krakenied** [comment]
@MiniMoro98 

```
  eeeeeeeeee:
    type: "inventory"
    amount: 1000000
    item: STONE
    exact-match: false
    remove-items-when-complete: true
    allow-partial-completion: true
```


https://github.com/LMBishop/Quests/assets/46192742/6836bb1b-6d4f-4042-813c-4c8774af64c0

@LMBishop the issue can be closed
