### ISSUE TITLE
Add the new brush in 1.20.1 in a task type

### ISSUE THREAD

**Issue by NoltoxGit** [LMBishop/Quests#544]
### Description of Feature

Hello,
Would it be possible to add integration of the new brush in the 1.20.1 in a task type please?

Example :
```yml
brush:
  type: "blockbrush"
  amount: 100                           # Number of brushed blocks
  blocks:                               # Name of blocks which will count towards progress
   - SAND
   - GRAVEL     
  worlds:                               # (OPTIONAL) restrict to certain worlds
  - "world"
```

### Reason for Addition

This could be a cool objective to put in a quest, as it would require a lot of exploration to find these blocks.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open
