### ISSUE TITLE
smithing task type does not work?

### ISSUE THREAD

**Issue by CrystallRPG** [LMBishop/Quests#575]
### Description of Bug

Task "smithing" does not work 

### Steps to Reproduce

Create a quest with smithing task type

### Environment

- Minecraft version: 1.20.1
- Server software: Paper 1.20.1-R0.1-Snapshot (Git 773dd72)
- Quests version: 3.14.2-be14387

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

tasks:
  task1:
    type: "smithing"
    amount: 1
    item: NETHERITE_HELMET
    
display:
  type: "NETHERITE_CHESTPLATE"
  name: "&2&m♦--------------------------------------------------♦"
  lore-normal:
    - ''
    - '§8 » &7Tipologia: &aGiornaliera'
    - ''
    - '§8 » &7Nome: &aSignore Della Guerra'
    - ''
    - '§8 » &7Obbiettivo: &aCrafta'
    - ''
    - ' &8&l•&a %quests_quest:QuestDaily9_task:task1_progress%&7/1&a Elmo Di Netherite'
    - ''
    - '&2&m♦--------------------------------------------------♦'
    - '&8 » &7Stato: &aIn corso'
    - '&8 » &7Tempo restante: &a%quests_quest:QuestDaily9_timeleft%'
    
    

options:
  category: "crystalsmp"
  repeatable: true
  time-limit: 
    enabled: true
    time: 1440
  cooldown:
    enabled: true
    time: 1440

**Comment by Krakenied** [comment]
If you want to create a Quest for an action like this
![image](https://github.com/LMBishop/Quests/assets/46192742/12c873ab-f512-4074-abc2-55fbba4a7d0e)
you should use the following config:
```
tasks:
  task1:
    type: smithing # type of the task
    item: NETHERITE_HELMET # the smithing result item
    amount: 1 # amount of items smithed
    mode: transform # to ignore trim actions
    exact-match: false # to ignore other nbt
```
