### ISSUE TITLE
ItemsAdder items are not recognized by the quests

### ISSUE THREAD

**Issue by pmeras** [LMBishop/Quests#576]
### Description of Bug

Hello, so recently I tried to make a quest with some itemsadder items but it doesn't work at all, either the bloc is not recognized or the quest just doesn't work.

I don't seems to find anybody who's done that so I'm kinda helpless. the plugin does mention the possibility to use it with itemsadder but I don't know how to do it.

### Steps to Reproduce

Here is my config file for the quest i tried with the Item "Ancient Enderite" from the pack enderiteexpansion.

```
tasks:
  mining:
    type: "blockbreak"
    id: "enderiteexpansion:ancient_enderite"
    amount: 100
    remove-items-when-complete: false
    reverse-if-placed: true
display:
  name: "&#acacacQuête de &#7500ed&ll&#8100ed&l'&#8c00ed&lE&#9800ee&ln&#a400ee&ld&#af00ee&le&#bb00ee&lr&#c700ef&li&#d200ef&lt&#de00ef&le &#ff0000&o#12"  
  lore-normal:
    - ""
    - "&7Votre objectif:"
    - "&2Cassez 100 minerais d'enderite"
    - ""
    - "&7Progrès:"
    - "&5{mining:progress}/100 minerais d'enderite"
    - ""
    - "&#3498dbRécompense:"
    - "&#e74c3c&o+100 000$"
    - ""
  lore-started:
    - "&e▲ La quête a été lancée."
  type: "itemsadder"
    id: "ancient_enderite"
    namespace: "enderiteexpansion"
```

Note : I have tried a bunch of things that didn't seems to work at all.

### Environment

- Minecraft version: 1.19.3
- Server software: Purpur 1.19.3 (Debian)
- Quests version: 3.14.2-3345d07

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
You have to create a file in `plugins/Quests/items/` directory and set its content to, for example:

`test123.yml`
```
type: itemsadder
item:
  id: "enderiteexpansion:ancient_enderite"
```
And then refer to it with:

`example-quest.yml`
```
tasks:
  test:
    type: "inventory"
    item:
      quest-item: "test123"
    amount: 100
```
It doesn't make you able to use it in block task types though (block comparisons check only the block material)
