### ISSUE TITLE
Consume task bug

### ISSUE THREAD

**Issue by RRRRzzzz2** [LMBishop/Quests#600]
### Description of Bug

You cannot complete a consume task quest by eating golden_apple, enchanted_golden_apple and probably more

### Steps to Reproduce

Configure the quest for task:consume golden_apple 
Eat golden apple

### Environment

- Minecraft version: 1.20.1
- Server software: Purpur
- Quests version:3.14.2-3345d07

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Works correctly
```
tasks:
  test:
    type: "consume"
    item: "ENCHANTED_GOLDEN_APPLE"
    amount: 100
```

https://github.com/LMBishop/Quests/assets/46192742/5a858c88-b5a5-4af1-96d8-dd666a9bd79f
