### ISSUE TITLE
Folia Async command error

### ISSUE THREAD

**Issue by DarkyG2** [LMBishop/Quests#601]
### Description of Bug

When doing this :
```YAML
custom-elements:
  "categories": # apply to the category "examples"
    2:
      display:
        name: "&cTutoriel"
        lore:
          - "&7Terminez les quêtes tutoriel pour"
          - "&7accéder à toutes les autres quêtes."
        type: "EMERALD_BLOCK"
      commands: 
        - "quests c tutorial_farming"
```

I'm getting this error: https://pastebin.com/Zn1mq4yc and the command isn't executed

### Steps to Reproduce

1. use that config and click on it:
```YAML
custom-elements:
  "categories": # apply to the category "examples"
    2:
      display:
        name: "&cTutoriel"
        lore:
          - "&7Terminez les quêtes tutoriel pour"
          - "&7accéder à toutes les autres quêtes."
        type: "EMERALD_BLOCK"
      commands: 
        - "quests c tutorial_farming"
```

### Environment

- Minecraft version: 1.20.4
- Server software: Folia
- Quests version: 3.14.2-35ae450

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

I'm on Folia 1.20.4
