### ISSUE TITLE
Add possibility to edit number format

### ISSUE THREAD

**Issue by NoltoxGit** [LMBishop/Quests#613]
### Description of Feature

Hello,
Would it be possible to add the ability to change the format of numbers in quests in the config of messages please ?

Exemple of config :
```yml
messages:
  # Set the format of all numbers related displays.
  # More informations: https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html
  number-format: '#,##0.00'
```

### Reason for Addition

To simplify the rounding of certain values and improve the display of quests.

### Alternative Solutions

Any

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
Is any number displayed in a weird way?

**Comment by NoltoxGit** [comment]
> Is any number displayed in a weird way?
It's not because of that, but because I'd like my values to be displayed with commas (to make it more visual), and not all glued together.

And I thought it would be nice to offer this way of editing the display of values, as do most plugins where it's possible to have values ("economy" plugins in an example).

![image](https://github.com/LMBishop/Quests/assets/75265787/8acebf83-1147-4838-8b3f-dc64b41d7918)

**Comment by WarnDa** [comment]
Allow to dsplay them with a space (like 1 038) would be fine for FR users :d

**Comment by NoltoxGit** [comment]
Hello @Krakenied,
Do you have any news about this ?

**Comment by Krakenied** [comment]
i think i managed to implement it

**Comment by Krakenied** [comment]
its in config.yml
```yml
number-formats:
  # decimal format used for processing float, double and BigDecimal placeholders
  floating:
    format: '#,##0.00'
    locale: 'en-US'
  # decimal format used for processing int, long and BigInteger placeholders
  integral:
    format: '#,##0'
    locale: 'en-US'
```
