### ISSUE TITLE
Different names for quests-menu

### ISSUE THREAD

**Issue by ardse** [LMBishop/Quests#622]
### Description of Feature

Hello, is there a way to modify the names of the quests-menu but to give a different one for each menu ?

### Reason for Addition

I want to put a custom GUI for each quest menu

### Alternative Solutions

No

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
What do you mean

**Comment by ardse** [comment]
![image](https://github.com/LMBishop/Quests/assets/157892928/178eba7d-2da5-49bb-9a6a-3eea39f180a8)
![image](https://github.com/LMBishop/Quests/assets/157892928/640ef664-0cd9-4fce-ab4d-6c7a721cd8a0)

I have two categories of quests. When I click on one, it opens a quest menu, the same for the other. But I would like to have different GUIs for each menu, so I need to have a different title on each. Look at the photo (don't mind the offset and textures, I haven't adjusted them).

**Comment by ardse** [comment]
Hello, any news ? thanks

**Comment by Nesseley** [comment]
I would also really like for this to be implemented!

Currently in config.yml:
```
  guinames:
    quests-category: "Category"
    quests-menu: "Quests"
```
This displays `Quests` as the name of the GUI in **all** categories you open with `/quests category <your-category>`
We are making custom GUIs. Which means we want a way to define what is displayed in each category.

Say I want to Display "Main Quests" in my category "Quests", while I want to display "Challenges" in another.
Examle config.yml:
```
  guinames:
    quests-category: "Category"
    quests-menu: "Quests"
    quests-category-<your-category-here>: "Quests"

    quests-category-quests: "Main Quests"
    quests-category-challenges: "Challenges"
```
Any categories not defined should fallback to the default `quests-menu: "Quests"`
