### ISSUE TITLE
Check coreprotect not working

### ISSUE THREAD

**Issue by DarkyG2** [LMBishop/Quests#632]
### Description of Bug

when using the coreprotect option from the blockbreak task it will sometime easily glitch out

### Steps to Reproduce

use that config:
```YAML
  1:
    type: "blockbreak"
    amount: 32
    block:
    - "SUGAR_CANE"
    check-coreprotect: true
    check-coreprotect-time: 20
```

and do this: https://gyazo.com/9e28f15ba86f414cabb6893ded6a8c56

### Environment

- Minecraft version: 1.20.4
- Server software: folia 1.20.4
- Quests version: 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

coreprotect version: 22.2
