### ISSUE TITLE
Tree issue with coreprotect

### ISSUE THREAD

**Issue by WarnDa** [LMBishop/Quests#647]
### Description of Bug

When you put a sappling on the floor and the tree growth, the first log do not count for the quest

### Steps to Reproduce

- use coreprotect
- use this task type : 
```
tasks:
  oaklog:
    type: "blockbreakcertain"
    check-coreprotect: true
    check-coreprotect-time: 1296000
    amount: 192
    block: OAK_LOG
 ```
- Do the same as the video
 Video here : 
https://youtu.be/knzjtFFjocw

### Environment

- Minecraft version: 1.20.4
- Server software: Paper
- Quests version: 3.15-10fc3ae

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
