### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by morloxist** [LMBishop/Quests#656]
### Description of Bug

Hi, I need some help. Permissions for the tasks are not working. Even if I have a category that requires a permise, the player can still open it and take the quest. I also set in config that the category should not show to players who don't have permisis.

### Steps to Reproduce

The plugin completely ignores permissions. Even if the player has no permissions, he can turn on any task. In the attached config there is one category where it even says that you need permissions for that category, even in the main config of the plugin it says that if the player doesn't have permissions for it, the category won't show up, it doesn't work either.

### Environment

- Minecraft version: 1.20.4
- Server software: Paper
- Quests version: v3.15-b636bef
[categories.txt](https://github.com/LMBishop/Quests/files/15105796/categories.txt)
[config.txt](https://github.com/LMBishop/Quests/files/15105798/config.txt)

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
`permission-required` is for category and not for the display:

valid example:
```yml
        - ""
        - "&a&l* &7Spuštěné úkoly z této kategorie: &7&n%quests_category:mesto_started%"        
      type: "BEDROCK"
    permission-required: true
```

invalid example:
```yml
        - ""
        - "&a&l* &7Spuštěné úkoly z této kategorie: &7&n%quests_category:mesto_started%"        
      type: "BEDROCK"
      permission-required: true

```
