### ISSUE TITLE
Placeholder for required points

### ISSUE THREAD

**Issue by leogianfagna** [LMBishop/Quests#658]
### Description of Feature

We have **{objective-name:progress}** to mark the process to player. But do we have **{objective-name:required}**?

### Reason for Addition

Would be much more easy to use this placeholder in menus and more optimized than writting the same thing several times.

### Alternative Solutions

Actual method:
```yml
placeholders:
  description: "&7Do something."
  progress: "&e{objective:progress}&7 / &e3800"
```

Suggestion:
```yml
placeholders:
  description: "&7Do something."
  progress: "&e{objective:progress}&7 / &e{objective:required}"
```

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open
