### ISSUE TITLE
Smithing mode "transform" don't work

### ISSUE THREAD

**Issue by leogianfagna** [LMBishop/Quests#677]
### Description of Bug

The smithing task type works fine but when I tried to specify the transform mode, doesn't work. This happens because the plugin can't read correctly, see below:

```yml
    type: "smithing"
    amount: 40
    mode: "transform"
    item: LEATHER_CHESTPLATE
```

![image](https://github.com/LMBishop/Quests/assets/142264317/200ea602-93e9-46ac-8c28-ff81a37ab69b)

I just specified the transform but it's saying that is trim mode, which is not.

### Steps to Reproduce

.

### Environment

- Minecraft version: Purpur 1.20.4
- Server software:
- Quests version: Quests version 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
