### ISSUE TITLE
block-break doesn't work with mushrooms

### ISSUE THREAD

**Issue by leogianfagna** [LMBishop/Quests#678]
### Description of Bug

If you create a task block-break and use mushroom_block (red or brown), will not work. I even try the debug but, in this case, nothing appers.

### Steps to Reproduce

Create this quest:

```yml
  colher-cogumarrom:
    type: "blockbreak"
    amount: 30
    blocks:
      - BROWN_MUSHROOM_BLOCK
    exact-match: false
```

Try it.

### Environment

- Minecraft version: Purpur 1;20.4
- Server software:
- Quests version: Quests version 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
