### ISSUE TITLE
[Suggestion] conditions to start quest

### ISSUE THREAD

**Issue by Slowedgg** [LMBishop/Quests#699]
### Description of Feature

It would be great if conditions could be added to start or auto-start quests.
Conditions could be variable comparison, permissions, or simply being able to add more requirements to the quest.
Currently it only allows to add one requirement:

```
options:
  # ...
  requires:
   - "quest-id"
```

### Reason for Addition

It is about fulfilling other conditions to be able to start a quest, without the need to have completed another specific quest.

### Alternative Solutions

operators:

For text:
(==, !=, equalsIgnoreCase, !equalsIgnoreCase, Contains)

For numbers:
(==, !=, <, >, <=, >=)

Example:

```
options:
  # ...
  conditions:
    placeholder: "%placeholder% operator evaluates"  
    placeholder: "%player_empty_slots% == 20"             
    permission-required: true
    requires:
     - "quest-id"
```

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open
