### ISSUE TITLE
I need some help (inventory is not working for me)

### ISSUE THREAD

**Issue by FightMan01** [LMBishop/Quests#73]
Hi! 
I need some help about this plugin. I tried t join to the discord server, but the invite expired.

So, I want to make a quest that gives 10 emerald to the player when he get a boat.
My config is:
```
tasks:
  boat:
    type: "inventory"
    amount: 1
    item: 333

(some display thing here)
```
I tried it with name (BOAT) and nothing happened.

My server is running on Spigot 1.12.2
I can start the quest, but when I get a boat it does nothing.
Please help me!
