### ISSUE TITLE
crafting GOLDEN_APPLE issue

### ISSUE THREAD

**Issue by Micosedeunha** [LMBishop/Quests#734]
### Description of Bug

I have this simple quest where the players should craft 5 golden apples. Recently I updated to 1.21.1 and this quest stopped working. I thought it had to do with some changes from 1.20.4 to 1.21 but with a simple test I changed the item to a GOLDEN_AXE and it worked just fine. I thing there is a problem with recognizing the line `item: GOLDEN_APPLE`. Despite this, I've set the icon to show a golden apple and it recognizes. Here is my quest code for you to check:

```
tasks:
  objetivo1:
    type: "crafting"
    amount: 5
    item: GOLDEN_APPLE                        
display:
  name: "&b(57) Negócio ta ficando chique"
  lore-normal:
    - "&7Esse objetivo requere que você:"
    - "&7 -Crafte &f5 &7maçãs douradas."
    - ""
    - "&7Recompensa:"
    - "&7 - &f3000$ &7de saldo."
    
  lore-started:
    - ""
    - "&7Progess:"
    - "&7 - &f{objetivo1:progress}&7/5."
  type: "GOLDEN_APPLE"
  
rewards:
  - "eco give {player} 3000"
placeholders:
  description: "&7Crafte &f5 &7maçãs douradas."
  progress: "&f{objetivo1:progress}&7/5 feitas"
  
options:
  category: "objetivos"
  repeatable: false
  cooldown:
    enabled: false
    # Time (in minutes)
    time: 1440
  sort-order: 57
```

### Steps to Reproduce

Just use my code and try to complete the task, you will se it wont work. Then change GOLDEN_APPLE to GOLDEN_AXE and it will work. Also my category is set to "objetivos" just to remind to change.

### Environment

- Minecraft version: Current Purpur Version: 1.21.1-2305-fdfc12e (MC: 1.21.1)
- Quests version: v3.15.2-b216e2b

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests
