### ISSUE TITLE
custom_model_data broken in 1.21.4

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#767]
### Description of Bug

MoJang changed custom_model_data in the latest version.
```
item:
        material: PAPER
        custom_model_data: 500
```
I updated my resourcepack and can spawn in the items via command and see them just fine, but the plugin only shows me a paper

### Steps to Reproduce

use minecraft 1.21.4 and try custom model data for items

### Environment

- Minecraft version: 1.21.4
- Server software: paper
- Quests version: 3.15.2-b216e2b

### Agreements

- [x] I am running the latest version of Quests
- [x] I am certain this issue is unique and a similar issue is not currently open
- [x] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Please import an example custom model item to quests (/q a items import) and show the item file contents

**Comment by Nesseley** [comment]
```
type: raw
item:
  ==: org.bukkit.inventory.ItemStack
  v: 4189
  type: FLOWER_BANNER_PATTERN
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    custom-model-data:
      ==: CustomModelData
      floats: []
      flags: []
      strings:
      - nokkel_vanlig
      colors: []

```
`nokkel_vanlig` is now the name of the custom model, istead of the previous number.
I spawn the item in with `/give Nesseley minecraft:flower_banner_pattern[minecraft:custom_model_data={strings:['nokkel_vanlig']}]`
