### ISSUE TITLE
Boats count for Walking Task with Walking Mode

### ISSUE THREAD

**Issue by MattDeWeerd** [LMBishop/Quests#800]
### Description of Bug

When a quest with the task walking and a mode of walking selected, moving in a boat counts towards the quest progress 

### Steps to Reproduce

Create a quest with:
```
    type: "walking"
    mode: walking
```

Activate the quest

Get in a boat and move

### Environment

- Minecraft version: 1.21.4
- Server software: Purpur
- Quests version: 3.15.2-7a37a3b

### Agreements

- [x] I am running the latest version of Quests
- [x] I am certain this issue is unique and a similar issue is not currently open
- [x] I am using a version of Minecraft which is supported by Quests

### Other

My quest config:
```
tasks:
  task1:
    type: "walking"
    distance: 500
    mode: walking

display:
  name: "&7&lWalking 2"
  lore-normal:
    - "&7 - Walk &f500 Blocks&7."
  lore-started:
    - ""
    - "&7Your current progression:"
    - "&7 - &f{task1:progress}&7/500 blocks walked."
  type: "PAPER"
  custommodeldata: 10020

rewards:
  - "eco give {player} 500"

placeholders:
  description: "&7Walk &f500 blocks &7."
  progress: "&#ff85e4{task1:progress}&7/&#ff85e4500 &7Steps."

options:
  category: "movement"
  requires:
    - "walking1"
  repeatable: false
  cooldown:
    enabled: true
    time: 1440
  sort-order: 2

```
