### ISSUE TITLE
Adding per-world support

### ISSUE THREAD

**Issue by mare-on** [LMBishop/Quests#88]
**Description of Problem**
This plugin is awesome but has one problem. If you are not using bungeecord, you can't separate doing quests per world. A lot of servers doesn't use bungeecord and if they has for example world with creative then they can't use this plugin because of players can do quests un-fair.

**Description of Feature**
There should be an option in config file called "**Allow in creative: true/false**" which could be fix doing quests in creative world.

**Alternative Methods**
There is one task called "**position**" which has tag called "**world**", is it possible to include this tag in all tasks?

**Comment by ImBas** [comment]
Really looking for per-world support too.
I think a cleaner fix would be to add it as option under 'options' at the bottom of the quests file like so:

```YAML
options:
  category: "somecategory"
  repeatable: false
  cooldown:
    enabled: false
    time: 1440
  sort-order: 1
  worlds:
  - world
  - world_nether
```
and for it to work for any world you just wouldn't add the 'worlds' setting under options, which in turn makes it backward-compatible with any previous versions and wouldn't be obstructive for inexperienced users who do not want to use it.

**Comment by ImBas** [comment]
@mare-on Update! Just figured out how to do this by using the latest version (2.9.5)

By using the task type placeholderapi_evaluate you can achieve this (see: https://github.com/LMBishop/Quests/wiki/Task-Configuration-Layout#placeholderapi_evaluate)

Here's how:
```YAML
  world:
    type: "placeholderapi_evaluate"
    placeholder: "%player_world%"
    evaluates: "your_world_name"
```

This solves as a temporary solution.
